// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/assignment/assignment.proto

package go_micro_srv_assignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExperimentName       string   `protobuf:"bytes,2,opt,name=experiment_name,json=experimentName,proto3" json:"experiment_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0feaacedf0ec52c7, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

type Response struct {
	Variant              string   `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0feaacedf0ec52c7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

type ExperimentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExperimentRequest) Reset()         { *m = ExperimentRequest{} }
func (m *ExperimentRequest) String() string { return proto.CompactTextString(m) }
func (*ExperimentRequest) ProtoMessage()    {}
func (*ExperimentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0feaacedf0ec52c7, []int{2}
}

func (m *ExperimentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentRequest.Unmarshal(m, b)
}
func (m *ExperimentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentRequest.Marshal(b, m, deterministic)
}
func (m *ExperimentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentRequest.Merge(m, src)
}
func (m *ExperimentRequest) XXX_Size() int {
	return xxx_messageInfo_ExperimentRequest.Size(m)
}
func (m *ExperimentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentRequest proto.InternalMessageInfo

func (m *ExperimentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ExperimentResponse struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Variants             []*ExperimentResponse_Variant `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ExperimentResponse) Reset()         { *m = ExperimentResponse{} }
func (m *ExperimentResponse) String() string { return proto.CompactTextString(m) }
func (*ExperimentResponse) ProtoMessage()    {}
func (*ExperimentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0feaacedf0ec52c7, []int{3}
}

func (m *ExperimentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentResponse.Unmarshal(m, b)
}
func (m *ExperimentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentResponse.Marshal(b, m, deterministic)
}
func (m *ExperimentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentResponse.Merge(m, src)
}
func (m *ExperimentResponse) XXX_Size() int {
	return xxx_messageInfo_ExperimentResponse.Size(m)
}
func (m *ExperimentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentResponse proto.InternalMessageInfo

func (m *ExperimentResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExperimentResponse) GetVariants() []*ExperimentResponse_Variant {
	if m != nil {
		return m.Variants
	}
	return nil
}

type ExperimentResponse_Variant struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Percentage           float64  `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExperimentResponse_Variant) Reset()         { *m = ExperimentResponse_Variant{} }
func (m *ExperimentResponse_Variant) String() string { return proto.CompactTextString(m) }
func (*ExperimentResponse_Variant) ProtoMessage()    {}
func (*ExperimentResponse_Variant) Descriptor() ([]byte, []int) {
	return fileDescriptor_0feaacedf0ec52c7, []int{3, 0}
}

func (m *ExperimentResponse_Variant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentResponse_Variant.Unmarshal(m, b)
}
func (m *ExperimentResponse_Variant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentResponse_Variant.Marshal(b, m, deterministic)
}
func (m *ExperimentResponse_Variant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentResponse_Variant.Merge(m, src)
}
func (m *ExperimentResponse_Variant) XXX_Size() int {
	return xxx_messageInfo_ExperimentResponse_Variant.Size(m)
}
func (m *ExperimentResponse_Variant) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentResponse_Variant.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentResponse_Variant proto.InternalMessageInfo

func (m *ExperimentResponse_Variant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExperimentResponse_Variant) GetPercentage() float64 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.assignment.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.assignment.Response")
	proto.RegisterType((*ExperimentRequest)(nil), "go.micro.srv.assignment.ExperimentRequest")
	proto.RegisterType((*ExperimentResponse)(nil), "go.micro.srv.assignment.ExperimentResponse")
	proto.RegisterType((*ExperimentResponse_Variant)(nil), "go.micro.srv.assignment.ExperimentResponse.Variant")
}

func init() { proto.RegisterFile("proto/assignment/assignment.proto", fileDescriptor_0feaacedf0ec52c7) }

var fileDescriptor_0feaacedf0ec52c7 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x56, 0x92, 0x3a, 0x05, 0xc5, 0xb9, 0x34, 0xf4, 0x20, 0xe9, 0x22, 0xb4, 0x28,
	0xac, 0x90, 0x9e, 0x3d, 0x78, 0x10, 0x11, 0xc1, 0x42, 0x0e, 0xde, 0xa4, 0xae, 0xed, 0x10, 0x72,
	0xc8, 0x6e, 0xdc, 0xdd, 0x16, 0x1f, 0xcd, 0xc7, 0x93, 0x66, 0xd3, 0x24, 0x60, 0x2b, 0xf6, 0xb6,
	0x33, 0xf3, 0xcf, 0xf7, 0xcf, 0x0c, 0x0b, 0xe3, 0x42, 0x2b, 0xab, 0x6e, 0x85, 0x31, 0x59, 0x2a,
	0x73, 0x92, 0xb6, 0xf5, 0xe4, 0x65, 0x0d, 0x87, 0xa9, 0xe2, 0x79, 0xb6, 0xd4, 0x8a, 0x1b, 0xbd,
	0xe1, 0x4d, 0x99, 0x3d, 0x43, 0x90, 0xd0, 0xe7, 0x9a, 0x8c, 0xc5, 0x21, 0x04, 0x6b, 0x43, 0x7a,
	0x91, 0xad, 0x42, 0x2f, 0xf2, 0xa6, 0xa7, 0x89, 0xbf, 0x0d, 0x9f, 0x56, 0x38, 0x81, 0x73, 0xfa,
	0x2a, 0x48, 0x67, 0xdb, 0x8e, 0x85, 0x14, 0x39, 0x85, 0xdd, 0x52, 0x70, 0xd6, 0xa4, 0x5f, 0x44,
	0x4e, 0xec, 0x0a, 0xfa, 0x09, 0x99, 0x42, 0x49, 0x43, 0x18, 0x42, 0xb0, 0x11, 0x3a, 0x13, 0xd2,
	0x56, 0xb4, 0x5d, 0xc8, 0x26, 0x70, 0xf1, 0x50, 0xf7, 0xed, 0xcc, 0x11, 0x4e, 0x4a, 0xb0, 0xd3,
	0x96, 0x6f, 0xf6, 0xed, 0x01, 0xb6, 0x95, 0x15, 0x79, 0x8f, 0x14, 0xe7, 0xd0, 0xaf, 0xf0, 0x26,
	0xec, 0x46, 0xbd, 0xe9, 0x20, 0x9e, 0xf1, 0x03, 0x2b, 0xf3, 0xdf, 0x48, 0xfe, 0xea, 0x7a, 0x93,
	0x1a, 0x32, 0xba, 0x83, 0xa0, 0x4a, 0xee, 0xf5, 0xbb, 0x04, 0x28, 0x48, 0x2f, 0x49, 0x5a, 0x91,
	0xba, 0x6b, 0x78, 0x49, 0x2b, 0x13, 0xbf, 0x01, 0xdc, 0xd7, 0x8e, 0x38, 0x07, 0xdf, 0x45, 0x18,
	0x1d, 0x9c, 0xaa, 0x3a, 0xc4, 0x68, 0xfc, 0x87, 0xc2, 0x4d, 0xcb, 0x3a, 0xb1, 0x82, 0x41, 0xb3,
	0x85, 0xc1, 0x77, 0xe8, 0x3d, 0x92, 0xc5, 0xeb, 0x7f, 0xad, 0xec, 0x6c, 0x6e, 0x8e, 0x38, 0x0f,
	0xeb, 0x7c, 0xf8, 0xe5, 0x37, 0x9a, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xab, 0x2c, 0x3a, 0xfa,
	0x6b, 0x02, 0x00, 0x00,
}
