// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/assignment/assignment.proto

package go_micro_srv_assignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExperimentName       string   `protobuf:"bytes,2,opt,name=experiment_name,json=experimentName,proto3" json:"experiment_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0feaacedf0ec52c7, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetExperimentName() string {
	if m != nil {
		return m.ExperimentName
	}
	return ""
}

type Response struct {
	Variant              string   `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0feaacedf0ec52c7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

// For Pub/Sub
type ExperimentEvent struct {
	// 0 - Created
	// 1 - deleted
	// 2 - updated
	Kind                 int32    `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExperimentEvent) Reset()         { *m = ExperimentEvent{} }
func (m *ExperimentEvent) String() string { return proto.CompactTextString(m) }
func (*ExperimentEvent) ProtoMessage()    {}
func (*ExperimentEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0feaacedf0ec52c7, []int{2}
}

func (m *ExperimentEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentEvent.Unmarshal(m, b)
}
func (m *ExperimentEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentEvent.Marshal(b, m, deterministic)
}
func (m *ExperimentEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentEvent.Merge(m, src)
}
func (m *ExperimentEvent) XXX_Size() int {
	return xxx_messageInfo_ExperimentEvent.Size(m)
}
func (m *ExperimentEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentEvent proto.InternalMessageInfo

func (m *ExperimentEvent) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *ExperimentEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.assignment.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.assignment.Response")
	proto.RegisterType((*ExperimentEvent)(nil), "go.micro.srv.assignment.ExperimentEvent")
}

func init() { proto.RegisterFile("proto/assignment/assignment.proto", fileDescriptor_0feaacedf0ec52c7) }

var fileDescriptor_0feaacedf0ec52c7 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x75, 0x8b, 0xb6, 0x3a, 0x87, 0x5d, 0x98, 0xcb, 0x16, 0x4f, 0xbb, 0x41, 0xd0, 0x53, 0x04,
	0xc5, 0x0f, 0xf0, 0xb0, 0x07, 0x11, 0x14, 0x72, 0x97, 0x25, 0x9a, 0x61, 0x19, 0x24, 0x49, 0x4d,
	0xd2, 0xe2, 0xe7, 0x4b, 0xd3, 0xda, 0x7a, 0x71, 0x6f, 0xf3, 0x32, 0xef, 0xe5, 0xbd, 0x37, 0xb0,
	0x6d, 0x82, 0x4f, 0xfe, 0x56, 0xc7, 0xc8, 0x07, 0x67, 0xc9, 0xa5, 0x3f, 0xa3, 0xcc, 0x3b, 0x5c,
	0x1f, 0xbc, 0xb4, 0xfc, 0x11, 0xbc, 0x8c, 0xa1, 0x93, 0xf3, 0x5a, 0x3c, 0x43, 0xa5, 0xe8, 0xab,
	0xa5, 0x98, 0x70, 0x0d, 0x55, 0x1b, 0x29, 0xec, 0xd9, 0xd4, 0x8b, 0xcd, 0xe2, 0xe6, 0x42, 0x95,
	0x3d, 0x7c, 0x32, 0x78, 0x0d, 0x2b, 0xfa, 0x6e, 0x28, 0x70, 0xaf, 0xd8, 0x3b, 0x6d, 0xa9, 0x2e,
	0x32, 0x61, 0x39, 0x3f, 0xbf, 0x68, 0x4b, 0xe2, 0x0a, 0xce, 0x15, 0xc5, 0xc6, 0xbb, 0x48, 0x58,
	0x43, 0xd5, 0xe9, 0xc0, 0xda, 0xa5, 0xf1, 0xb7, 0x5f, 0x28, 0x1e, 0x60, 0xb5, 0x9b, 0x74, 0xbb,
	0x8e, 0x5c, 0x42, 0x84, 0xd3, 0x4f, 0x76, 0x83, 0xef, 0x99, 0xca, 0x33, 0x2e, 0xa1, 0x60, 0x33,
	0x1a, 0x15, 0x6c, 0xee, 0xde, 0x00, 0x1e, 0xa7, 0xdc, 0xf8, 0x0a, 0xe5, 0x80, 0x70, 0x23, 0xff,
	0xe9, 0x26, 0xc7, 0x62, 0x97, 0xdb, 0x23, 0x8c, 0x21, 0xad, 0x38, 0x79, 0x2f, 0xf3, 0xa1, 0xee,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xfb, 0x8c, 0x29, 0x4d, 0x01, 0x00, 0x00,
}
